import type { RunReport } from '../core/types.js';
import { renderTranscript } from '../judge/prompts.js';
import { countLongPauses } from './metrics.js';
import type { RunDiff } from './diff.js';

/** Markdown report — shareable with a client or pasted into a PR. */
export function renderMarkdownReport(report: RunReport, diff?: RunDiff): string {
  const lines: string[] = [];
  const { totals } = report;
  const rate = totals.scenarios === 0 ? 0 : Math.round((totals.passed / totals.scenarios) * 100);

  lines.push(`# Voice agent test report — ${report.agentName ?? report.agentId}`);
  lines.push('');
  lines.push(`- Run: \`${report.runId}\` · Suite: \`${report.suiteId}\` · ${report.startedAt}`);
  lines.push(`- **${totals.passed}/${totals.scenarios} scenarios passed (${rate}%)**${totals.errored ? ` · ${totals.errored} errored` : ''}`);
  lines.push(`- Estimated LLM spend on your keys: $${report.llmCostUsd.toFixed(4)}`);
  if (report.unpricedLlmCalls) {
    lines.push(`- ⚠️ ${report.unpricedLlmCalls} call(s) used models without pricing data — actual spend is higher than shown`);
  }
  const pauses = countLongPauses(report);
  if (pauses > 0) {
    lines.push(`- ⏱ ${pauses} agent response(s) took >1.5s — callers experience these as dead air`);
  }
  lines.push('');

  if (diff) {
    lines.push('## Change vs previous run');
    lines.push('');
    lines.push(`Pass rate: ${Math.round(diff.passRateBefore * 100)}% → ${Math.round(diff.passRateAfter * 100)}%`);
    lines.push('');
    if (diff.regressions.length > 0) {
      lines.push('| Regression | Category | Before → After |');
      lines.push('|---|---|---|');
      for (const r of diff.regressions) lines.push(`| ${r.title} | ${r.category} | ${r.before} → **${r.after}** |`);
      lines.push('');
    }
    if (diff.fixes.length > 0) {
      lines.push('| Fixed | Category | Before → After |');
      lines.push('|---|---|---|');
      for (const f of diff.fixes) lines.push(`| ${f.title} | ${f.category} | ${f.before} → **${f.after}** |`);
      lines.push('');
    }
    if (diff.changed.length > 0) {
      lines.push('| Changed | Category | Before → After |');
      lines.push('|---|---|---|');
      for (const c of diff.changed) lines.push(`| ${c.title} | ${c.category} | ${c.before} → **${c.after}** |`);
      lines.push('');
    }
    if (diff.regressions.length === 0 && diff.fixes.length === 0 && diff.changed.length === 0) {
      lines.push('No scenario changed verdict.');
      lines.push('');
    }
  }

  lines.push('## Scenario results');
  lines.push('');
  lines.push('| Verdict | Scenario | Category | Persona | Caller experience |');
  lines.push('|---|---|---|---|---|');
  for (const o of report.outcomes) {
    const verdict = o.judge ? (o.judge.scenarioVerdict === 'pass' ? '✅ pass' : '❌ fail') : '⚠️ error';
    const exp = o.judge
      ? `${o.judge.experience.resolutionQuality}, effort ${o.judge.experience.callerEffort}, abandonment ${o.judge.experience.abandonmentRisk}`
      : '—';
    lines.push(`| ${verdict} | ${o.scenario.title} | ${o.scenario.category} | ${o.scenario.persona} | ${exp} |`);
  }
  lines.push('');

  for (const o of report.outcomes) {
    lines.push(`### ${o.judge?.scenarioVerdict === 'pass' ? '✅' : o.judge ? '❌' : '⚠️'} ${o.scenario.title}`);
    lines.push('');
    if (o.judge) {
      lines.push(o.judge.summary);
      lines.push('');
      const failures = o.judge.verdicts.filter((v) => v.verdict === 'fail');
      if (failures.length > 0) {
        lines.push('Failed criteria:');
        for (const v of failures) {
          const criterion = o.scenario.successCriteria.find((c) => c.id === v.criterionId);
          lines.push(`- **${criterion?.description ?? v.criterionId}** — ${v.reasoning}${v.evidence && v.evidence !== 'none' ? ` (evidence: "${v.evidence}")` : ''}`);
        }
        lines.push('');
      }
    } else if (o.call.error) {
      lines.push(`Call errored: ${o.call.error}`);
      lines.push('');
    }
    lines.push('<details><summary>Transcript</summary>');
    lines.push('');
    lines.push('```');
    lines.push(renderTranscript(o.call));
    lines.push('```');
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by benchcall. Testing evidence, not legal advice; no test suite catches every failure.*');
  return lines.join('\n');
}
